import { inkDescription, layerInkHex } from './inks'
import { BY_SKU, GRID, inventoryLabel, layerCounts, plateSize, plateTransform, validate } from './model'
import { renderPlacement } from './art'
import type { Layer, Project } from './types'
export const escapeXml = (s: string) => s.replace(/[<>&"']/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;' })[c]!)
export const policyLabel = (p: Project) => p.design.inventoryMode === 'concurrent' ? 'Concurrent assembly: sum across passes' : 'Reuse pieces: maximum needed in any pass'
export function plateSvg(project: Project, layer: Layer) {
  const { w, h } = plateSize(project.design)
  const gridLines = Array.from({ length: GRID.cols + 1 }, (_, x) => `M${x},0V${GRID.rows}`).join(' ') + ' ' + Array.from({ length: GRID.rows + 1 }, (_, y) => `M0,${y}H${GRID.cols}`).join(' ')
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w * GRID.pitch_mm}mm" height="${h * GRID.pitch_mm}mm" viewBox="0 0 ${w} ${h}"><title>${escapeXml(layer.name)} · mirrored setup</title><desc>${escapeXml(policyLabel(project))}. ${escapeXml(inkDescription(layer))}. Provisional corner mask and rectangular footprints. Vendor artwork orientation unverified. ${validate(project).length ? 'DRAFT: unresolved build issues.' : 'Checks pass under provisional assumptions.'}</desc><g transform="${plateTransform(project.design, true)}"><path d="${gridLines}" fill="none" stroke="#ccccbb" stroke-width="0.015"/>${GRID.blocked_cells.map(([x,y]) => `<rect x="${x}" y="${y}" width="1" height="1" fill="#ddd5c5"/>`).join('')}${layer.placements.map(p => renderPlacement(p, layerInkHex(layer))).join('')}</g><rect x="0.025" y="0.025" width="${w - .05}" height="${h - .05}" fill="none" stroke="#66665c" stroke-width=".05"/></svg>`
}
export function buildSheetHtml(project: Project) {
  const issues = validate(project)
  const { w, h } = plateSize(project.design)
  const pages = project.design.layers.map((layer, index) => `<section><header><span>PRIXEL / SETUP SHEET</span><span>PASS ${index + 1} OF ${project.design.layers.length}</span></header><h1>${escapeXml(project.design.name)}</h1><h2>${escapeXml(layer.name)} · ${escapeXml(layerInkHex(layer))}</h2><p>${escapeXml(inkDescription(layer))}</p><p>${escapeXml(policyLabel(project))}</p><p>${project.design.inventoryMode === 'reuse' ? 'Dismantle and clean pieces between passes before reuse.' : 'All passes reserve pieces together. More than two passes require extra setup plates or a revised assembly plan.'}</p><p class="warning">${issues.length ? `DRAFT: ${issues.length} unresolved build issue(s).` : 'Checks pass under provisional assumptions.'} Corner cutouts, rectangular footprints and vendor artwork orientation need physical confirmation.</p><p>↑ TOP OF SETUP PLATE · MIRRORED · ${w * 5} × ${h * 5} mm</p><div class="plate">${plateSvg(project, layer)}</div><div class="ruler">50 mm calibration</div><p>Print at 100% / actual size. Turn off “fit to page”. Measure the ruler before assembly.</p><h3>Pick-list</h3><table><thead><tr><th>Piece</th><th>Description</th><th>Quantity</th></tr></thead><tbody>${Object.entries(layerCounts(layer)).map(([sku, n]) => `<tr><td>${escapeXml(inventoryLabel(sku))}</td><td>${escapeXml(BY_SKU[sku].description)}</td><td>${n}</td></tr>`).join('') || '<tr><td colspan="3">This pass is empty.</td></tr>'}</tbody></table>${issues.length ? `<p class="warning">${issues.map(i => escapeXml(i.message)).join('<br/>')}</p>` : ''}<footer>Paper preview: ${escapeXml(project.design.paperColor)}. Screen colours and covering overprint are illustrative, not measured print predictions. Mono: shared physical pools; 323 counted versus 324 stated. Acute substitutes use the quote piece and print noticeably high.</footer></section>`).join('')
  return `<!doctype html><html lang="en"><meta charset="utf-8"><title>${escapeXml(project.design.name)} · PRIXEL build sheets</title><style>body{font:12px system-ui;color:#30302a;background:#e8e5dd;margin:0}section{background:#fffdf7;box-sizing:border-box;width:190mm;margin:16px auto;padding:12mm;break-after:page}section:last-child{break-after:auto}header{display:flex;justify-content:space-between;letter-spacing:1px;font-size:10px}h1{font-size:23px;margin-bottom:5px}h2{font-size:15px}p{line-height:1.5;margin:6px 0}.plate{width:max-content;margin:12px 0}.plate svg{display:block;max-width:none}.ruler{box-sizing:border-box;width:50mm;border:1px solid;border-top:0;text-align:center;height:5mm;margin-top:8mm}.warning{color:#8a382a}table{border-collapse:collapse;width:100%;font-size:11px}th,td{text-align:left;padding:4px;border-bottom:1px solid #ddd}footer{font-size:10px;margin-top:16px;line-height:1.5}@page{size:A4;margin:10mm}@media print{body{background:transparent}section{margin:0;padding:0;width:auto}.actions{display:none}}</style><div class="actions" style="padding:16px;text-align:center">Use your browser’s Print command to print or save as PDF. Each ink pass starts on a new page.</div>${pages}</html>`
}
export function download(contents: string, name: string, mime: string) {
  const url = URL.createObjectURL(new Blob([contents], { type: mime }))
  const a = document.createElement('a'); a.href = url; a.download = name; a.click()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
export function fileStem(name: string) { return name.replace(/[^\p{L}\p{N}_-]+/gu, '-').slice(0, 80) || 'prixel' }
